### ISSUE TITLE
Spamming Console with errors/not working for some people

### ISSUE THREAD

**Issue by Daxz0** [Hydroxycobalamin/Denizen-Script-Collection#6]
### I confirm that...

- [X] I have tested the reproducion steps on a vanilla client, with the Server-Resourcepack enabled.
- [X] Checked the issues page for similar issues. This Bug report won't be a duplicate.

### Script

None

### Expected Behavior

You should be able to use the items and not have errors spamming in console.

### Actual Behavior

Errors spam in console.

### Steps to reproduce

1. Log onto server
2. Hold out the stick item
3. Errors will spam

### Additional Information

https://paste.denizenscript.com/View/109837

Debug Log

**Comment by Hydroxycobalamin** [comment]
Fixed.
