### ISSUE TITLE
Grouping Display Entities

### ISSUE THREAD

**Issue by Daxz0** [Hydroxycobalamin/Denizen-Script-Collection#7]
### I confirm that...

- [X] I checked the issues page for similar issues. This Feature request won't be a duplicate.
- [X] I made sure that this feature does not exist yet by asking on the Discord or reading the Wiki.

### Script

Item Display Editor

### Description

Players can choose a group option where then they can click and group entities together. Left click to group, right click to ungroup. Grouping will allow players to easily move a set of display entities.

**Comment by Hydroxycobalamin** [comment]
Added the features you want with a whole GUI and handling in 60b310e.
